name: Tinymovr Firmware Check/Build

on: [push]

jobs:
  check-and-build-fw:
    runs-on: 'ubuntu-22.04'
    strategy:
      matrix:
        board-revision: [R32, R33, R50, R51, R52, M51]
    steps:
    - uses: actions/checkout@v2
    - uses: carlosperate/arm-none-eabi-gcc-action@v1

    - name: Set up Python 3.10
      uses: actions/setup-python@v2
      with:
        python-version: "3.10"

    - name: Install dependencies
      run: |
        sudo apt-get install cppcheck
        python -m pip install --upgrade pip
        python -m pip install patch

    - name: Run cppcheck on Tinymovr
      run: cppcheck --force --addon=cert --error-exitcode=1 -isrc/rtt -isrc/utils -isrc/nvm -isrc/uart -isrc/can src
      working-directory: firmware

    - name: Clone Qorvo deps
      uses: actions/checkout@v2
      with: 
        repository: yconst/qorvo-deps
        token: ${{ secrets.ACCESS_TOKEN }}
        path: 'firmware/pac55xx_sdk'
        clean: false

    - name: Patch deps dir
      run: |
        python -m patch sdk_patch.patch
      working-directory: firmware 

    - name: Build Debug
      run: |
        make debug REV=${{ matrix.board-revision }}
        make clean
      working-directory: firmware
    
    - name: Build Upgrade Image
      run: |
        make upgrade REV=${{ matrix.board-revision }}
        make clean
      working-directory: firmware

    - name: Build Release
      run: |
        make release REV=${{ matrix.board-revision }}
        make clean
      working-directory: firmware
